name: Import shared helm charts to ACR

on:
  workflow_dispatch :
    inputs:
      ACR_NAME:
        description: 'ACR Name'
        required: true
        default: 'helmchartpocacr'
        type: string
      SUBSCRIPTION:
        description: 'Subscription ID'
        required: true
        default: 'a2d83027-e216-42fb-adab-6868a86f2d8e'
        type: string
      CHART_REPO_PATH: 
        description: 'The Path to repo containing Helm charts'
        required: true
        default: 'nginxinc'
        type: string
      CHECKOUT_BRANCH:
        description: 'The branch from which helm charts need to be extracted from eg: main or master'
        required: true
        default: 'main'
        type: string
      CHART_DIRECTORY_PATH:
        description: 'The Path of parent folder that contains Helm Charts'
        required: true
        default: 'kubernetes-ingress'
        type: string
      CHART_PATH: 
        description: 'The Path of the helm folder'
        required: true
        default: 'charts/nginx-ingress'
        type: string
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Checkout Helm Repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.event.inputs.CHART_REPO_PATH }}/${{ github.event.inputs.CHART_DIRECTORY_PATH }}'
          path: './${{ github.event.inputs.CHART_DIRECTORY_PATH }}/'
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: '${{ github.event.inputs.CHECKOUT_BRANCH }}'
          
      - name: Install Azure CLI
        run: |
          sudo apt-get install azure-cli
      
      - name : Install Helm 
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          environment: ${{ inputs.environment }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Helm Login
        id: HelmLogin
        run: |
          az account set --subscription ${{ github.event.inputs.SUBSCRIPTION }}
          az acr login --name ${{ github.event.inputs.ACR_NAME }}
    
      - name : Helm package Helm templates
        id : HelmPkg
        run: |
          cd ./${{ github.event.inputs.CHART_DIRECTORY_PATH }}/${{ github.event.inputs.CHART_PATH }}
          helm package .
          echo "HELM_CHART_PKG_PATH = $(helm package . | cut -d: -f2)" >> "$GITHUB_ENV"

      - name: Helm push to ACR
        run: |
           helm push "${{ env.HELM_CHART_PKG_PATH }}"  oci://${{ github.event.inputs.ACR_NAME }}.azurecr.io/helm

