name: Import shared helm charts to ACR

on:
   workflow_dispatch:
    inputs:
      enviornment1:
        description: 'GitHub Environment to pull action secrets from'
        required: true
        type: environment
   push:
        
   workflow_call:
    inputs:
      environment:
         required: true
         default: muskan-acr-env
         type: string
      acr_name:
        required: true
        default: helmchartpocacr.azurecr.io
        type: string
      subscription:
        required: true
        default: a2d83027-e216-42fb-adab-6868a86f2d8e
        type: string
      tenant_name:
        required: true
        type: string
      user_name:
        required: true
        default: helmchartpocacradmin
        type: string
      repo_name:
        required: true
        default: helm-poc
        type: string
      target_name:
        required: true
        default: kubernetes-ingress/charts/nginx-ingress
        type: string
env:
  TEMPLATES_REPO: nginxinc/kubernetes-ingress
  TEMPLATES_REPO_2: external-secrets/kubernetes-external-secrets

jobs:
  build:
    runs-on: ubuntu-latest
    environment : ${{ inputs.environment}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Checkout kubernetes-ingress/nginx-ingress
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATES_REPO }}
          path: './kubernetes-ingress/'
          token: ${{ secrets.ACCESS_TOKEN || github.token }}
          ref: main
          
      - name: Checkout external-secrets/kubernetes-external-secrets
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATES_REPO_2 }}
          path: './kubernetes-external-secrets/'
          token: ${{ secrets.ACCESS_TOKEN || github.token }}
          ref: master
        

      - name: Install Azure CLI
        run: |
          sudo apt-get install azure-cli
      
      - name : Install Helm 
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          environment: ${{ inputs.environment }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Helm Login
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az acr login --name ${{ secrets.ACR_NAME }}
          # export HELM_EXPERIMENTAL_OCI=1
          # TOKEN=$(az acr login --name ${{ secrets.ACR_NAME }} --expose-token --output tsv --query accessToken)
          # echo $TOKEN | helm registry login ${{ secrets.ACR_NAME }}.azurecr.io \
          #   --username 00000000-0000-0000-0000-000000000000 \
          #   --password-stdin
      
      - name : Helm package
        run: |
          cd ./kubernetes-ingress/charts/nginx-ingress
          echo "packagef1 = $(helm package . | cut -d: -f2)" >> "$GITHUB_ENV"
          helm package .
          # cd ../../
          # cd ./helm/helm-templates
          # # echo "packagef2 = $(helm package .)" >> $GITHUB_ENV
          # helm package .
          
      - name : Helm package second template
        run: |
          cd ./kubernetes-external-secrets/charts/kubernetes-external-secrets
          helm package .
     
          
          
      # - name : Saving helm packages as artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name:  contoso-helm-template
      #     path: /home/runner/work/helm-poc/helm-poc/helm-chart-poc/helm/contoso-helm-template/contoso-helm-template-0.1.0.tgz
          
      # - name : Saving helm packages as artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name:  helm-templates
      #     path: /home/runner/work/helm-poc/helm-poc/helm-chart-poc/helm/helm-templates/contoso-helm-template-0.1.0.tgz
          
      # - name: Download all workflow run artifacts
      #   uses: actions/download-artifact@v4

      - name: Helm push to ACR
        run: |
      
          helm push  oci://${{ secrets.ACR_NAME }}.azurecr.io/helm
          helm push  oci://${{ secrets.ACR_NAME }}.azurecr.io/helm

