name: test workflow

on:
  workflow_dispatch:
    inputs:
      TEST_YAML:
        required: true
        default: 'please work'
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
       - name: Save Env variable
         id: test
         run: |
            echo "PKG_PATH = something something"
            echo "::set-output name=pkg_path::$PKG_PATH"
            echo "colour=test" >> "$GITHUB_ENV"

       - name: Get env
         run: | 
          
           echo "PKG_PATH from previous step: ${{ steps.test.outputs.pkg_path }}"
           echo "here is to hoping this works and give me the colour : $colour"
         
      
        
        
        
        
