name: test workflow

on:
  workflow_dispatch:
    inputs:
      TEST_YAML:
        required: true
        default: 'please work'
        type: string
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
       - name: Save Env variable
         id: test
         run: |
            echo "colour = test" >> "$GITHUB_OUTPUT"

       - name: Get env
         run: | 
           echo "here is to hoping this works and give me the colour : ${{ steps.test.outputs.colour }}"
         
      
        
        
        
        
